eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: LoginProvider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zkz
    password: Kk147258..
    url: jdbc:mysql://47.99.194.112:3306/db_ljb?serverTimezone=UTC&characterEncoding=UTF8
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9902


  jmx:
    default-domain:server:
    default-domain: UserLoginService
endpoints:
  jmx:
    domain: UserLoginService
    unique-names: true