eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: ApiLoginConsumer

  jmx:
    default-domain:server:
    default-domain: LoginAPI

  port: 9802
feign:
  httpclient:
    enabled: true

